### ISSUE TITLE
Produces this error on start

### ISSUE THREAD

**Issue by AliMickey** [timvisee/send#56]
My send instance was not working correctly last week, did some testing and doesn't turn out to be related to Docker.

To reproduce: without Docker 
1. Clone the git
2. npm install
3. npm start

Error:
```(node:15456) UnhandledPromiseRejectionWarning: Error: no such file or directory
    at MemoryFileSystem.readFileSync (D:\Programming\Git\send_temp\node_modules\memory-fs\lib\MemoryFileSystem.js:107:10)
    at getManifest (D:\Programming\Git\send_temp\common\assets.js:35:31)
    at Object.getAssetWithMiddleware [as get] (D:\Programming\Git\send_temp\common\assets.js:42:19)
    at module.exports (D:\Programming\Git\send_temp\server\state.js:44:28)
    at index (D:\Programming\Git\send_temp\server\routes\pages.js:13:28)
    at Layer.handle [as handle_request] (D:\Programming\Git\send_temp\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Programming\Git\send_temp\node_modules\express\lib\router\route.js:137:13)
    at module.exports (D:\Programming\Git\send_temp\server\middleware\language.js:41:3)
    at Layer.handle [as handle_request] (D:\Programming\Git\send_temp\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Programming\Git\send_temp\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\Programming\Git\send_temp\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\Programming\Git\send_temp\node_modules\express\lib\router\layer.js:95:5)
    at D:\Programming\Git\send_temp\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\Programming\Git\send_temp\node_modules\express\lib\router\index.js:335:12)
    at next (D:\Programming\Git\send_temp\node_modules\express\lib\router\index.js:275:10)
    at textParser (D:\Programming\Git\send_temp\node_modules\body-parser\lib\types\text.js:69:7)
(node:15456) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15456) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I think this is causing the same issue with my container, i get a 502 bad gateway and i cant even get any log output from send either.

**Comment by AliMickey** [comment]
fixed with latest release
