### ISSUE TITLE
docker-compose up issue on fresh start

### ISSUE THREAD

**Issue by Avskum** [timvisee/send#71]
Hi,

I just tryed fresh compose and I have this issue. Is this known bug?
```

Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 126, in perform_command
  File "compose/cli/main.py", line 1070, in up
  File "compose/cli/main.py", line 1066, in up
  File "compose/project.py", line 615, in up
  File "compose/service.py", line 350, in ensure_image_exists
  File "compose/service.py", line 376, in image
  File "docker/utils/decorators.py", line 17, in wrapped
docker.errors.NullResource: Resource ID was not provided
[1252319] Failed to execute script docker-compose
```

**Comment by Avskum** [comment]
I am stupid I did not saved .env file.
